### DISCUSSION TITLE
Namecheap 1011102 - API Key is invalid or API access has not been enabled

### DISCUSSION THREAD

**Discussion by OdinVex** [adferrand/dnsrobocert#1186] [Q&A] [answered]
API is enabled, my IP is whitelisted, API key is valid...wondering if DNSroboCert or Lexicon forcibly changes username case?

**Comment by OdinVex** [comment]
Config looks like this:

```
---  
draft: false # Test config file for validity
acme:
  email_account: administrator@mydomain.tld
  staging: true # Test for LetsEncrypt
  certs_permissions:
    files_mode: 0640
    dirs_mode: 0755
profiles:
  - name: ProfileName
    provider: namecheap
    provider_options:  
      auth_token: <removed>
      auth_username: UpperLowerCaseName
      auth_client_ip: WhitelistedIPv4OfRequester
      auth_sandbox: true # Testing for Namecheap
certificates:
  - name: ProfileName
    profile: ProfileName
    domains:
      - "*.mydomain.tld"
      - mydomain.tld 
    reuse_key: true
    key_type: rsa
```
