### ISSUE TITLE
Basic linux tools for deploy_hook

### ISSUE THREAD

**Issue by ThomDietrich** [adferrand/dnsrobocert#1014]
Hey there,
I need to use the `deploy_hook` functionality to copy generated certificates to a place and name which another application expects. To that end I've defined something similar to this:

```yaml
certificates:
  - domains:
       - ui.kntinternet.de
     deploy_hook: cp /etc/letsencrypt/live/mydomain.de/privkey.pem /etc/letsencrypt/privkey.pem
```

Upon execution I receive the error:

      dnsrobocert-1  | Hook 'deploy-hook' reported error code 1
      dnsrobocert-1  | Hook 'deploy-hook' ran with error output:
      dnsrobocert-1  |  /bin/sh: 1:  cp: not found

Could you please provide basic commands like `cp` with the container? Thanks!
