### ISSUE TITLE
Inconsistency between docs and source files with docker-compose.yml 

### ISSUE THREAD

**Issue by D4ggerfall** [adferrand/dnsrobocert#102]
In the docs (https://dnsrobocert.readthedocs.io/en/latest/user_guide.html#docker-compose) the following configuration is used:

```yml
version: '2'
services:
  dnsrobocert:
    image: adferrand/dnsrobocert
    container_name: dnsrobocert
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - /etc/dnsrobocert:/etc/dnsrobocert
    restart: always
```
In the sources at `compose/docker-compose.yml` this configuration is used:

```yml
  
version: '3.7'

services:
  dnsrobocert:
    image: adferrand/dnsrobocert
    container_name: dnsrobocert
    env_file: .env
    volumes:
      - $ROOT/dnsrobocert.yml:/etc/letsencrypt/dnsrobocert.yml
      - $ROOT/:/etc/letsencrypt
    environment:
      - VERSION=latest
    restart: always
```

The most important change here I see is that the mounted volume of the configuration file `/etc/dnsrobocert/config.yml` changed to `/etc/letsencrypt/dnsrobocert.yml`. Did the implementation change here? I was using the `docker-compose.yml` referenced in the docs and I noticed that changing the mounted `/etc/dnsrobocert/config.yml` didn't trigger a reconfiguration, but changing `/etc/letsencrypt/dnsrobocert.yml` did in fact trigger a reconfiguration, however initial configuration did work with `/etc/dnsrobocert/config.yml`. Could you clarify the intended behaviour here?
