### ISSUE TITLE
Usage with docker-compose: unable to get certificates in host

### ISSUE THREAD

**Issue by sineverba** [adferrand/dnsrobocert#107]
Hi!
I really appreciate your work!
I'm trying the docker with docker-compose:

```yml
dnsrobocert:
    image: adferrand/dnsrobocert:3.2.0
    container_name: dnsrobocert
    restart: always
    volumes:
      - ./config/dnsrobocert/letsencrypt:/etc/letsencrypt
      - ./config/dnsrobocert/dnsrobocert:/etc/dnsrobocert
    networks: 
      - "default"
      - "proxy-tier"
```

You can see that I map folder to a local folder inside my project and not to the `/etc/ folder.

The folders are created at first `docker-compose up` and owned by root (I run docker and docker-compose in non sudo mode) but live, logs etc folders are empty.

If I map the folder to /etc in host, the folders have the certificates, logs etc.

I didn't inspect the container, but **I'm sure it has the certs 'cause at next launch it logs that "Certificate not yes due for renewal. No action taken".**

My question is: How can I map to another folder other than /etc ?

Another question: I cannot figure why in your instructions there are 2 domains section:

```yml
certificates:
- domains:
  - mail.example.net
  - ldap.example.net
  profile: henet_profile
- domains:
  - "*.example.net"
  - example.net
```

This is my config, I imagine it is right:

```yml
draft: false
acme:
  email_account: ...@gmail.com
  staging: false
profiles:
- name: cloudflare
  provider: cloudflare
  provider_options:
    auth_token: Lq............................vIVJ
certificates:
- domains:
  - www.mycustomdomain.it
  profile: cloudflare
```

Thank you!
