### ISSUE TITLE
3.26.x crashes on start up

### ISSUE THREAD

**Issue by sjdaws** [adferrand/dnsrobocert#1292]
Since the 3.26.0/1 release robocert crashes on start up.

Config: 

```yaml
acme:
  certs_permissions:
    dirs_mode: 0755
    files_mode: 0644
    group: nogroup
    user: nobody
  email_account: <removed>
certificates:
- domains:
  - <removed>
  pfx:
    export: true
  profile: cloudflare
profiles:
- name: cloudflare
  provider: cloudflare
  provider_options:
    auth_token: <removed>
```

Logs: 

```sh
+ robocert robocert-d687d6fd8-lncz5 › robocert
robocert robocert-d687d6fd8-lncz5 robocert 2025-04-15 20:02:45 robocert-d687d6fd8-lncz5 dnsrobocert.core.main[1] INFO Starting DNSroboCert.
robocert robocert-d687d6fd8-lncz5 robocert 2025-04-15 20:02:45 robocert-d687d6fd8-lncz5 dnsrobocert.core.main[1] INFO Registering ACME account if needed.
robocert robocert-d687d6fd8-lncz5 robocert ----------
robocert robocert-d687d6fd8-lncz5 robocert 2025-04-15 20:02:45 robocert-d687d6fd8-lncz5 dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python3 -m dnsrobocert.core.certbot register -n --user-agent-comment DNSroboCert/3.26.1 --preferred-chain "ISRG Root X1" --config-dir /etc/letsencrypt --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs -m <removed> --agree-tos --server https://acme-v02.api.letsencrypt.org/directory
- robocert robocert-d687d6fd8-lncz5 › robocert
+ robocert robocert-d687d6fd8-lncz5 › robocert
robocert robocert-d687d6fd8-lncz5 robocert 2025-04-15 20:04:18 robocert-d687d6fd8-lncz5 dnsrobocert.core.main[1] INFO Starting DNSroboCert.
robocert robocert-d687d6fd8-lncz5 robocert 2025-04-15 20:04:18 robocert-d687d6fd8-lncz5 dnsrobocert.core.main[1] INFO Registering ACME account if needed.
robocert robocert-d687d6fd8-lncz5 robocert ----------
robocert robocert-d687d6fd8-lncz5 robocert 2025-04-15 20:04:18 robocert-d687d6fd8-lncz5 dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python3 -m dnsrobocert.core.certbot register -n --user-agent-comment DNSroboCert/3.26.1 --preferred-chain "ISRG Root X1" --config-dir /etc/letsencrypt --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs -m <removed> --agree-tos --server https://acme-v02.api.letsencrypt.org/directory
- robocert robocert-d687d6fd8-lncz5 › robocert
```

It ends up in a crash backoff loop with the same log printed over and over.

Is there a new config setting I'm missing? I've tried adding `dynamic_zone_resolution: false` to the profile and it didn't make a difference.

Thanks!
